<?php

/**
 * @file
 * Civicase Quotations exported searhform.
 */

return [
  [
    'name' => 'SavedSearch_Civicase_Quotations',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Civicase_Quotations',
        'label' => 'Civicase Quotations',
        'form_values' => NULL,
        'search_custom_id' => NULL,
        'api_entity' => 'CaseSalesOrder',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'client_id.display_name',
            'quotation_date',
            'description',
            'owner_id.display_name',
            'CONCAT_WS(" ", total_before_tax, currency:label) AS CONCAT_WS_total_before_tax_currency_label',
            'CONCAT_WS(" ", total_after_tax, currency:label) AS CONCAT_WS_total_after_tax_currency_label',
            'status_id:label',
          ],
          'orderBy' => [
            'created_at' => 'DESC',
          ],
          'where' => [
            [
              'case_id',
              'IS EMPTY',
            ],
          ],
          'groupBy' => [],
          'join' => [],
          'having' => [],
          'limit' => 10,
        ],
        'expires_date' => NULL,
        'description' => NULL,
        'mapping_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Civicase_Quotations_SearchDisplay_Civicase_Quotations_Table',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Civicase_Quotations_Table',
        'label' => 'Quotations List',
        'saved_search_id.name' => 'Civicase_Quotations',
        'type' => 'table',
        'settings' => [
          'actions' => TRUE,
          'limit' => 10,
          'classes' => [
            'table',
            'table-striped',
          ],
          'pager' => [],
          'placeholder' => 5,
          'sort' => [],
          'columns' => [
            [
              'type' => 'field',
              'key' => 'id',
              'dataType' => 'Integer',
              'label' => 'ID',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'client_id.display_name',
              'dataType' => 'String',
              'label' => 'Client',
              'sortable' => TRUE,
              'link' => [
                'path' => '',
                'entity' => 'Contact',
                'action' => 'view',
                'join' => 'client_id',
                'target' => '_blank',
              ],
              'title' => 'View Client',
            ],
            [
              'type' => 'field',
              'key' => 'quotation_date',
              'dataType' => 'Timestamp',
              'label' => 'Date',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'description',
              'dataType' => 'Text',
              'label' => 'Description',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'owner_id.display_name',
              'dataType' => 'String',
              'label' => 'Owner',
              'sortable' => TRUE,
              'link' => [
                'path' => '',
                'entity' => 'Contact',
                'action' => 'view',
                'join' => 'owner_id',
                'target' => '_blank',
              ],
              'title' => 'View Owner',
            ],
            [
              'type' => 'field',
              'key' => 'CONCAT_WS_total_before_tax_currency_label',
              'dataType' => 'String',
              'label' => 'Total Before Tax',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'CONCAT_WS_total_after_tax_currency_label',
              'dataType' => 'String',
              'label' => 'Total After Tax',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'status_id:label',
              'dataType' => 'Integer',
              'label' => 'Status',
              'sortable' => TRUE,
            ],
            [
              'text' => 'Actions',
              'style' => 'default',
              'size' => 'btn-sm',
              'icon' => 'fa-bars',
              'links' => [
                [
                  'path' => '',
                  'icon' => 'fa-external-link',
                  'text' => 'View',
                  'style' => 'default',
                  'condition' => [],
                  'entity' => 'CaseSalesOrder',
                  'action' => 'view',
                  'join' => '',
                  'target' => 'crm-popup',
                ],
                [
                  'entity' => 'CaseSalesOrder',
                  'action' => 'view',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-external-link',
                  'text' => 'Edit',
                  'style' => 'default',
                  'path' => '',
                  'condition' => [],
                ],
                [
                  'entity' => 'CaseSalesOrder',
                  'action' => 'delete',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-trash',
                  'text' => 'Delete',
                  'style' => 'danger',
                  'path' => '',
                  'condition' => [],
                ],
              ],
              'type' => 'menu',
              'alignment' => 'text-right',
            ],
          ],
        ],
        'acl_bypass' => FALSE,
      ],
    ],
  ],
];
